// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItem } from "./ThreadItem";

export type ThreadItemEntry = {
/**
 * Turn containing this item.
 */
turnId: string,
/**
 * Unix timestamp (in milliseconds) when this item was first persisted.
 *
 * Older app-server versions omit this field.
 */
createdAtMs: number | null, item: ThreadItem, };
