// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Turn } from "./Turn";
import type { TurnInputSource } from "./TurnInputSource";

export type TurnStartedNotification = { threadId: string, turn: Turn,
/**
 * Identifies which app-server input path started this turn.
 */
inputSource?: TurnInputSource, };
